version: '3.6'

services:

  database:
    image: "mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04"
    command: /bin/bash ./entrypoint.sh
    container_name: protheus_mssql
    environment:
      SA_PASSWORD: Asdwasdw22!
      ACCEPT_EULA: "Y"
      MSSQL_DB: PROTHEUS_33
    volumes:
      - ./docker/mssql/entrypoint.sh:/entrypoint.sh
      - ./docker/mssql/dbinit.sh:/dbinit.sh
      - ./docker/mssql/dbinit.sql:/dbinit.sql
    ports:
      - 1433:1433

  license:
    image: danielolalb/totvs_protheus_ls
    container_name: protheus_license
    
  dbaccess:
    image: viniciusgati/dbaccess_21_1_1_1:latest
    container_name: protheus_dbaccess
    ports:
      - 7890:7890
    environment:
      - DB_TYPE=mssql
      - DB_HOST=protheus_mssql
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASS=Asdwasdw22!
      - DB_NAME=protheus_33
    depends_on: 
      - database
      - license

  appserver:
    image: viniciusgati/appserver_20_3_0_8
    container_name: protheus_appserver
    ports:
      - 9999:9999
      - 5433:5433
    environment:
      - DBACCESS_SERVER=protheus_dbaccess
      - DBACCESS_ALIAS=PROTHEUS_33
    volumes:
      - ./docker/protheus12/protheus/apo:/totvs12/protheus/apo
      - ./docker/protheus12/protheus_data:/totvs12/protheus_data
    depends_on: 
      - dbaccess
      - license

volumes:
  mssql_data: {}
