USE master
GO
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '$(MSSQL_DB)')
BEGIN
  CREATE DATABASE $(MSSQL_DB);
END;
GO
RESTORE DATABASE $(MSSQL_DB) FROM  DISK = N'/P12133MNTDBEXP.bak' WITH  FILE = 1,  MOVE N'P12133MNTDBEXP' TO N'/var/opt/mssql/data/PROTHEUS_33.mdf',  MOVE N'P12133MNTDBEXP_log' TO N'/var/opt/mssql/data/PROTHEUS_33_log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5
GO